# Generated by Django 2.0.7 on 2018-07-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('externaltools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExternalTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalTool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='externaltools.ExternalTool')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Profile')),
            ],
        ),
    ]
