# Generated by Django 2.0.7 on 2018-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20180717_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltool',
            name='user_token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
