# Generated by Django 2.0.7 on 2018-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20180717_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexternaltool',
            name='user_token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
