# Generated by Django 2.0.7 on 2018-07-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20180718_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexternaltool',
            old_name='externalTool',
            new_name='external_tool',
        ),
    ]
