# Generated by Django 2.0.7 on 2018-07-21 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_auto_20180718_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltool',
            name='user_access_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), null=True, size=8),
        ),
    ]
