# Generated by Django 2.0.7 on 2018-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_userexternaltool_user_access_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternaltool',
            name='user_access_info',
        ),
        migrations.AlterField(
            model_name='userexternaltool',
            name='user_token',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
