# Generated by Django 2.0.7 on 2018-07-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_auto_20180721_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaultWordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_set_id', models.IntegerField(null=True)),
                ('user_external_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.UserExternalTool')),
            ],
        ),
    ]
