# Generated by Django 2.0.7 on 2018-07-22 09:36

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0011_userdefaultwordset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdefaultwordset',
            name='user_external_tool',
        ),
        migrations.AddField(
            model_name='userdefaultwordset',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
