# Generated by Django 2.0.7 on 2018-07-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alpha_2', models.CharField(max_length=2)),
                ('alpha_3', models.CharField(max_length=3)),
                ('country_code', models.IntegerField()),
                ('region', models.CharField(max_length=15)),
                ('sub_region', models.CharField(max_length=30)),
                ('region_code', models.IntegerField()),
                ('sub_region_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('alpha_2', models.CharField(max_length=2)),
                ('alpha_3', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('translation_text', models.CharField(max_length=50)),
                ('full_original_sentence', models.TextField()),
                ('original_language_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='words.Language')),
                ('translation_language_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='words.Language')),
            ],
        ),
    ]
